services:
  - type: web
    name: cruise-analysis
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -c gunicorn_config.py cruise_app:server
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
